{% set data = load_setup_py_data() %}

package:
  name: "pymt_heatc"
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy 1.11.*
    - model_metadata
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - bmi-tester
    - model_metadata
  imports:
    - pymt_heatc
  commands:
    - config_file=$(mmd-stage HeatModel . > MANIFEST && mmd-query HeatModel --var=run.config_file.path)
    - bmi-test pymt_heatc.bmi:HeatModel --config-file=$config_file --manifest=MANIFEST -v

about:
  summary: Python package that wraps the C Heat model BMI.
  home: https://github.com/pymt-lab/pymt_heatc
  license: MIT License
  license_file: LICENSE
  dev_url: https://github.com/pymt-lab/pymt_heatc
