# A conda environment for re/building a C pymt-lab component with Meson.
name: cbld
channels:
  - conda-forge
dependencies:
  - python =3
  - pip
  - make
  - cmake         # [bmi-example-c]
  - pkg-config
  - bmi-c
  - c-compiler
  - cxx-compiler  # [win]
  - cython
  - meson-python
  - python-build
  - numpy
  - bmi-tester >=0.5.5
  - pymt >=1.3.2
