name: Test

on: [push, pull_request]

jobs:
  build-test-unix:
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: latest
          environment-file: environment.yml

      - name: Build and install HeatModelC
        run: |
          mkdir build && pushd build
          cmake ../external/bmi-example-c -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
          make install
          popd

      - name: Build and install project
        run: |
          make install

      - name: Test imports
        working-directory: ${{ github.workspace }}/examples
        run: |
          python -c 'import pymt_heatc'
          python -c 'from pymt.models import HeatModelC'

      - name: Test BMI
        run: |
          make test

      - name: Run examples
        working-directory: ${{ github.workspace }}/examples
        run: |
          python heatc_ex.py
          python pymt_heatc_ex.py
